language: cpp
env:
  global:
      - DEVELOPER_ID_CERTIFICATE_P12="deploy/developer-id.p12"

cache:
  directories:
    - $TRAVIS_BUILD_DIR/src/
matrix:
  include:
  - os: linux
    dist: bionic
    before_install:
    - sudo apt-get update -qq
    - sudo apt-get install devscripts build-essential lintian dh-make
    - sudo apt-get install qt5-default libqt5quick5 libqt5qml5 qtdeclarative5-dev libqt5x11extras5-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-gl gstreamer1.0-libav gstreamer1.0-qt5 libqt5concurrent5 qml-module-qt-labs-settings qml-module-qtquick-controls2 qml-module-qtquick-layouts qml-module-qtquick-controls qml-module-qtquick-shapes qml-module-qtlocation qml-module-qtpositioning qml-module-qtquick-dialogs 
    - sudo apt-get install libgstreamer1.0-0 libgstreamer1.0-dev gstreamer1.0-gl gstreamer1.0-alsa gstreamer1.0-plugins-base libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-good libgstreamer-plugins-good1.0-dev
    compiler:
    - gcc
    script:
    - echo $TRAVIS_TAG
    - qmake QOpenHD.pro CONFIG+=release
    - make
  - os: osx
    osx_image:  xcode11.2
    before_install:
    - openssl aes-256-cbc -K $encrypted_9ef4f27e2944_key -iv $encrypted_9ef4f27e2944_iv -in deploy/developer-id.p12.enc -out ${DEVELOPER_ID_CERTIFICATE_P12} -d
    - export KEYCHAIN=build.keychain;
    - security create-keychain -p openhd ${KEYCHAIN}
    - security default-keychain -s ${KEYCHAIN}
    - security unlock-keychain -p openhd ${KEYCHAIN}
    - security set-keychain-settings -t 3600 -u $KEYCHAIN
    - security import ${DEVELOPER_ID_CERTIFICATE_P12} -k ${KEYCHAIN} -P "" -T /usr/bin/codesign

    - brew install qt5
    - brew link qt5 --force
    - mkdir -p src
    - if ! [ -f ./src/gstreamer-1.0-1.14.4-x86_64.pkg ]; then travis_wait curl -v -o ./src/gstreamer-1.0-1.14.4-x86_64.pkg https://gstreamer.freedesktop.org/data/pkg/osx/1.14.4/gstreamer-1.0-1.14.4-x86_64.pkg; fi
    - if ! [ -f ./src/gstreamer-1.0-devel-1.14.4-x86_64.pkg ]; then travis_wait curl -v -o ./src/gstreamer-1.0-devel-1.14.4-x86_64.pkg https://gstreamer.freedesktop.org/data/pkg/osx/1.14.4/gstreamer-1.0-devel-1.14.4-x86_64.pkg; fi
    - echo "Cached source dir:"
    - ls -l ./src/
    - echo "Installing GStreamer"
    - sudo installer -package ./src/gstreamer-1.0-1.14.4-x86_64.pkg -target /
    - sudo installer -package ./src/gstreamer-1.0-devel-1.14.4-x86_64.pkg -target /
    script:
    - qmake QOpenHD.pro CONFIG+=release
    - make -j5
  - os: windows
    before_install:
    - dir C:/Program\ Files\ \(x86\)/Windows\ Kits/10/bin/10.0.17134.0/x64
    - cmd.exe /C 'cd && "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"
      x86 && cd && cd "C:/Users/travis/build/infincia/QOpenHD" && dir'
    - curl -LfsS -o /tmp/travis-wait-enhanced.zip "https://github.com/crazy-max/travis-wait-enhanced/releases/download/v1.1.0/travis-wait-enhanced_1.1.0_windows_x86_64.zip"
    - 7z x /tmp/travis-wait-enhanced.zip -y -o/usr/bin/ travis-wait-enhanced.exe -r
    - travis-wait-enhanced --version
    - curl -vLO http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe
    - travis-wait-enhanced install_qt.bat
    - ls -la C:/Qt/5.12.5/msvc2017/bin/qtenv2.bat
    script:
    - cmd.exe /C 'cd && "C:\Qt\5.12.5\msvc2017\bin\qtenv2.bat" && cd && "C:\Program
      Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"
      x86 && cd "C:\Users\travis\build\infincia\QOpenHD" && cd && qmake QOpenHD.pro
      && nmake'

