name: build_package_rock5

on:
  push:
    branches: [ "2.3-evo" ]
  pull_request:
    branches: [ "2.3-evo" ]

jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-22.04
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - name: Add environment variables
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV    
             
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Build Package
        run: |
          git clone https://github.com/OpenHD/ChrootCompilationTest /opt/ChrootCompilationTest
          git clone -b 2.3-evo https://github.com/OpenHD/QOpenHD --recursive /opt/ChrootCompilationTest/additionalFiles
          echo $CLOUDSMITH_API_KEY > /opt/ChrootCompilationTest/additionalFiles/cloudsmith_api_key.txt
          cd /opt/ChrootCompilationTest/
          sudo bash install_dep.sh
          sudo bash build.sh rock5 $API_KEY
