name: Build Jetson Selfhosted


on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: build Qopenhd
      run: |
        ls -a
        sudo apt update
        sudo bash install_dep.sh
        sudo ./package.sh arm64 ubuntu bionic
        ls -a 

    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "QopenHD"
        path: |
          *.deb
          *.log
        if-no-files-found: error

      - name: Push
      id: push
      uses: cloudsmith-io/action@master
        with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-2-evo"
        distro: "ubuntu"
        release: "bionic"
        republish: "true" # needed ONLY if version is not changing
        file: "*.deb"
        

      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
