name: Build Jetson ONLINE

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
   
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Emulating Jetson
      id: qemu
      uses: pguyot/arm-runner-action@1be4bc9de8a7ba3c1c4f5bf917c438e8dc97904b
      with:
        base_image: http://openhdfpv.org/wp-content/BaseImages/Open.HD-2.1-05221841-jetson-nano-4gb-bionic.img.zip
        cpu: cortex-a53
        bootpartition:
        rootpartition: 1
        image_additional_mb: 4000
        copy_repository_path: /opt
        copy_artifact_path: Open.HD
        import_github_env: true
        commands: |
            ls -a
            cd /opt
            cd QOpenHD
            apt update
            apt -y install openhd-qt-jetson-nano
            sudo ./install_dep.sh
            ln -s /opt/Qt5.15.0 /opt/Qt5.15.4
            sudo ./package.sh arm64 ubuntu bionic
            ls -a

    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "QOpenHd"
        path: |
          QOpenHD/*.deb

    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-1-alpha"
        distro: "ubuntu"
        release: "bionic"
        republish: "true" # needed ONLY if version is not changing
        file: "QOpenHD/*.deb"
          
      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
