name: Build Jetson ONLINE

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [self-hosted, linux, X64]
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
   
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Install packages
      run: sudo apt-get install -y sudo udev gdisk
    
    - name: Emulating Jetson
      id: qemu
      uses: pguyot/arm-runner-action@1be4bc9de8a7ba3c1c4f5bf917c438e8dc97904b
      with:
        base_image: http://openhdfpv.org/wp-content/BaseImages/Open.HD-2.1-05221841-jetson-nano-4gb-bionic.img.zip
        cpu: cortex-a53
        bootpartition:
        rootpartition: 1
        image_additional_mb: 4000
        copy_repository_path: /opt
        copy_artifact_path: Open.HD
        import_github_env: true
        commands: |
          ls -a
          cd /opt/QOpenHD
          apt update
          apt install -y curl
          curl -1sLf 'https://dl.cloudsmith.io/public/openhd/openhd-2-1-alpha/gpg.9D1C80E55B50390B.key' | apt-key add -
          curl -1sLf \
            'https://dl.cloudsmith.io/public/openhd/openhd-2-1-alpha/setup.deb.sh' \
            | sudo -E bash
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo add-apt-repository ppa:mhier/libboost-latest -y
          sudo add-apt-repository ppa:git-core/ppa -y
          apt update
          apt install -y openhd-qt-jetson-nano-bionic 
          apt upgrade -y
          sudo bash install_dep.sh
          sudo ./package.sh arm64 ubuntu bionic
          ls -a  
          

    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-2-evo"
        distro: "ubuntu"
        release: "bionic"
        republish: "true" # needed ONLY if version is not changing
        file: "QOpenHD/*.deb"
  cleanup:
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    steps:
      - name: Cleanup
        run: losetup -d /dev/loop*